### ISSUE TITLE
Clarification: `suspensions`

### ISSUE THREAD

**Issue by slightlynybbled** [tgray/weibull#1]
Greetings -

I like the collection of functions that you have put together.  I am attempting to port to python3 and I am also doing a fair amount of cleanup, but I had a couple of clarification questions before getting started.

Q: A `suspension` is defined as a test in which the unit was run for a time but did not fail, therefore, there was no failure event observed?

In other words, the following would be a valid instantiation of units in test vs. fail times:

```python
# create table of failure times at test initialization
units_in_test = 9
fail_times = [None] * units_in_test   # when test is started, there are no failure times

# tabulated failure times, hours
fail_times[8] = 6677
fail_times[0] = 8329
fail_times[1] = 8545

# a suspension is when a unit is removed from test before it has failed
suspensions = [False if x else True for x in fail_times]

analysis = weibull.Weibull(fail_times, suspensions=suspensions)
```

**Comment by tgray** [comment]
That is correct.  

Say you test 10 units for 10,000 cycles when the testing is stopped.  Only 8 fail in that time span.  The two that don't fail are suspended.

Very cool that you are picking this up and doing something with it.  I'll have to look at the code at some point.
